model:
  model_save_name: "thermo_tf"

  training_type: "density_estimation" # density_estimation or classification

  model_type: "unet"

  in_out_filters: 16

  batch_norm: False
  conv_transpose: False
  squeeze: False
  double_double_conv: True

  input_shape: [24, 32, 1]

  optimizer: "adam"
  loss: "mae" # mae, mse, categorical_crossentropy
  metrics: ["mae", "mse"]

  batch_size: 64
  epochs: 1000
  early_stopping_patience: 25

dataset:
  data_generator: "v2" # v1 or v2
  training_dirs:
    [
      "006__11_44_59",
      "007__11_48_59",
      "008__11_52_59",
      "009__11_57_00",
      "000__14_15_19",
      "001__14_19_19",
      "002__14_23_19",
      "003__14_27_20",
      "004__14_31_20",
      "012__15_03_21",
      "013__15_07_21",
      "014__15_11_21",
      "015__15_15_21",
      "016__15_19_21",
      "011__13_38_20",
      "012__13_42_20",
      "013__13_46_21",
      "007__13_22_20",
    ]

  validation_dirs:
    [
      "004__13_10_20",
      "014__13_50_21",
      "005__14_35_20",
      "006__14_39_20",
      "007__14_43_20",
      "008__14_47_20",
    ]

  test_dirs:
    [
      "008__13_26_20",
      "009__14_51_20",
      "010__14_55_20",
      "011__14_59_20",
      "015__13_54_21",
    ]

  IR_camera_resolution: [24, 32]
  temperature_normalization_min: 20
  temperature_normalization_max: 35
  sum_of_values_for_one_person: 51.35
  max_people_count: 6
